const quizData = {
  Technology: [
    {
      id: 1,
      question: "Which of the following is a frontend framework?",
      options: ["Django", "React", "Node.js", "Laravel"],
      answer: "React",
    },
    {
      id: 2,
      question: "What does HTTP stand for?",
      options: [
        "HyperText Transfer Protocol",
        "Hyper Transfer Text Process",
        "HyperText Transmission Process",
        "High Transfer Text Protocol",
      ],
      answer: "HyperText Transfer Protocol",
    },
    {
      id: 3,
      question: "Which company developed the Windows operating system?",
      options: ["Apple", "Google", "Microsoft", "IBM"],
      answer: "Microsoft",
    },
    {
      id: 4,
      question: "What does CSS stand for?",
      options: [
        "Creative Style Sheets",
        "Cascading Style Sheets",
        "Computer Style Syntax",
        "Central Style System",
      ],
      answer: "Cascading Style Sheets",
    },
    {
      id: 5,
      question: "Which of the following is a version control system?",
      options: ["Jenkins", "Git", "Docker", "Kubernetes"],
      answer: "Git",
    },
    {
      id: 6,
      question: "Which tag is used to define a hyperlink in HTML?",
      options: ["<a>", "<link>", "<href>", "<url>"],
      answer: "<a>",
    },
    {
      id: 7,
      question: "Which cloud service does Microsoft provide?",
      options: ["AWS", "Azure", "Google Cloud", "DigitalOcean"],
      answer: "Azure",
    },
    {
      id: 8,
      question: "What language is primarily used for iOS app development?",
      options: ["Kotlin", "Swift", "Java", "Dart"],
      answer: "Swift",
    },
    {
      id: 9,
      question: "What is the main purpose of Docker?",
      options: [
        "Database Management",
        "Containerization",
        "UI Design",
        "Source Control",
      ],
      answer: "Containerization",
    },
    {
      id: 10,
      question: "What does API stand for?",
      options: [
        "Application Programming Interface",
        "Automated Process Integration",
        "Advanced Programming Interaction",
        "Application Program Input",
      ],
      answer: "Application Programming Interface",
    },
  ],
  Business: [
    {
      id: 1,
      question: "Who is known as the father of modern management?",
      options: ["Peter Drucker", "Elon Musk", "Henry Ford", "Steve Jobs"],
      answer: "Peter Drucker",
    },
    {
      id: 2,
      question: "What does ROI stand for in business?",
      options: [
        "Rate of Investment",
        "Return on Investment",
        "Revenue on Income",
        "Return of Input",
      ],
      answer: "Return on Investment",
    },
    {
      id: 3,
      question: "Which company’s slogan is 'Just Do It'?",
      options: ["Adidas", "Nike", "Puma", "Reebok"],
      answer: "Nike",
    },
    {
      id: 4,
      question: "What is the full form of CEO?",
      options: [
        "Chief Executive Officer",
        "Corporate Executive Organizer",
        "Chief Economic Officer",
        "Company Executive Officer",
      ],
      answer: "Chief Executive Officer",
    },
    {
      id: 5,
      question: "What is the term for a market controlled by one seller?",
      options: ["Monopoly", "Oligopoly", "Duopoly", "Competition"],
      answer: "Monopoly",
    },
    {
      id: 6,
      question: "Which company owns LinkedIn?",
      options: ["Meta", "Google", "Microsoft", "Amazon"],
      answer: "Microsoft",
    },
    {
      id: 7,
      question: "What is the primary goal of marketing?",
      options: [
        "Increase sales",
        "Develop software",
        "Reduce expenses",
        "Hire employees",
      ],
      answer: "Increase sales",
    },
    {
      id: 8,
      question: "What does B2B stand for?",
      options: [
        "Business to Business",
        "Buyer to Buyer",
        "Business to Buyer",
        "Bank to Bank",
      ],
      answer: "Business to Business",
    },
    {
      id: 9,
      question: "Which of these is a financial statement?",
      options: [
        "Income Statement",
        "Job Description",
        "Advertisement Copy",
        "Business Proposal",
      ],
      answer: "Income Statement",
    },
    {
      id: 10,
      question: "Which company founder is Jeff Bezos?",
      options: ["Amazon", "Tesla", "Google", "Apple"],
      answer: "Amazon",
    },
  ],
  General: [
    {
      id: 1,
      question: "What is the capital of France?",
      options: ["London", "Berlin", "Paris", "Madrid"],
      answer: "Paris",
    },
    {
      id: 2,
      question: "Which planet is known as the Red Planet?",
      options: ["Mars", "Venus", "Jupiter", "Saturn"],
      answer: "Mars",
    },
    {
      id: 3,
      question: "Who wrote the national anthem of India?",
      options: [
        "Mahatma Gandhi",
        "Rabindranath Tagore",
        "Sarojini Naidu",
        "Bankim Chandra Chatterjee",
      ],
      answer: "Rabindranath Tagore",
    },
    {
      id: 4,
      question: "How many continents are there on Earth?",
      options: ["5", "6", "7", "8"],
      answer: "7",
    },
    {
      id: 5,
      question: "Which ocean is the largest?",
      options: ["Atlantic", "Indian", "Pacific", "Arctic"],
      answer: "Pacific",
    },
    {
      id: 6,
      question: "What is H2O commonly known as?",
      options: ["Oxygen", "Hydrogen", "Water", "Salt"],
      answer: "Water",
    },
    {
      id: 7,
      question: "Which country is called the Land of Rising Sun?",
      options: ["China", "Japan", "Thailand", "Korea"],
      answer: "Japan",
    },
    {
      id: 8,
      question: "What is the largest mammal in the world?",
      options: ["Elephant", "Blue Whale", "Shark", "Giraffe"],
      answer: "Blue Whale",
    },
    {
      id: 9,
      question: "Who invented the telephone?",
      options: [
        "Alexander Graham Bell",
        "Thomas Edison",
        "Nikola Tesla",
        "Isaac Newton",
      ],
      answer: "Alexander Graham Bell",
    },
    {
      id: 10,
      question: "Which festival is known as the Festival of Lights?",
      options: ["Holi", "Diwali", "Eid", "Christmas"],
      answer: "Diwali",
    },
  ],
  Entertain: [
    {
      id: 1,
      question: "Who directed the movie 'Inception'?",
      options: ["Christopher Nolan", "James Cameron", "Spielberg", "Tarantino"],
      answer: "Christopher Nolan",
    },
    {
      id: 2,
      question: "Which superhero is known as 'The Dark Knight'?",
      options: ["Superman", "Iron Man", "Batman", "Spider-Man"],
      answer: "Batman",
    },
    {
      id: 3,
      question: "Which streaming platform produced 'Stranger Things'?",
      options: ["Amazon Prime", "Netflix", "Disney+", "Hulu"],
      answer: "Netflix",
    },
    {
      id: 4,
      question: "Who is known as the 'King of Pop'?",
      options: ["Elvis Presley", "Michael Jackson", "Justin Bieber", "Eminem"],
      answer: "Michael Jackson",
    },
    {
      id: 5,
      question: "Which movie features the song 'Let It Go'?",
      options: ["Moana", "Frozen", "Tangled", "Cinderella"],
      answer: "Frozen",
    },
    {
      id: 6,
      question: "Which sport is shown in the movie 'Chak De! India'?",
      options: ["Cricket", "Hockey", "Football", "Kabaddi"],
      answer: "Hockey",
    },
    {
      id: 7,
      question: "Who played Iron Man in the Marvel movies?",
      options: [
        "Robert Downey Jr.",
        "Chris Evans",
        "Mark Ruffalo",
        "Tom Holland",
      ],
      answer: "Robert Downey Jr.",
    },
    {
      id: 8,
      question: "Which movie won the Oscar for Best Picture in 2020?",
      options: ["1917", "Parasite", "Joker", "Ford v Ferrari"],
      answer: "Parasite",
    },
    {
      id: 9,
      question: "What is the Hogwarts house of Harry Potter?",
      options: ["Slytherin", "Hufflepuff", "Ravenclaw", "Gryffindor"],
      answer: "Gryffindor",
    },
    {
      id: 10,
      question: "Who is the director of 'Avatar'?",
      options: ["James Cameron", "Ridley Scott", "Peter Jackson", "Nolan"],
      answer: "James Cameron",
    },
  ],
  Education: [
    {
      id: 1,
      question: "What is 5 + 7?",
      options: ["10", "11", "12", "13"],
      answer: "12",
    },
    {
      id: 2,
      question: "What is the chemical symbol of Gold?",
      options: ["Ag", "Au", "Gd", "Go"],
      answer: "Au",
    },
    {
      id: 3,
      question: "Who is known as the father of physics?",
      options: ["Einstein", "Newton", "Galileo", "Tesla"],
      answer: "Newton",
    },
    {
      id: 4,
      question: "What is the capital of India?",
      options: ["Mumbai", "Delhi", "Kolkata", "Chennai"],
      answer: "Delhi",
    },
    {
      id: 5,
      question: "Who discovered gravity?",
      options: ["Galileo", "Einstein", "Newton", "Copernicus"],
      answer: "Newton",
    },
    {
      id: 6,
      question: "What is the square root of 49?",
      options: ["6", "7", "8", "9"],
      answer: "7",
    },
    {
      id: 7,
      question: "What gas do plants produce during photosynthesis?",
      options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
      answer: "Oxygen",
    },
    {
      id: 8,
      question: "Which is the largest planet in our solar system?",
      options: ["Earth", "Jupiter", "Mars", "Saturn"],
      answer: "Jupiter",
    },
    {
      id: 9,
      question: "Who wrote 'A Brief History of Time'?",
      options: [
        "Stephen Hawking",
        "Albert Einstein",
        "Isaac Newton",
        "Marie Curie",
      ],
      answer: "Stephen Hawking",
    },
    {
      id: 10,
      question: "Which instrument is used to measure temperature?",
      options: ["Barometer", "Thermometer", "Altimeter", "Hygrometer"],
      answer: "Thermometer",
    },
  ],
  Lifestyle: [
    {
      id: 1,
      question: "How many hours of sleep are recommended for adults?",
      options: ["4-5", "6-8", "8-10", "10-12"],
      answer: "6-8",
    },
    {
      id: 2,
      question: "Which vitamin is produced when exposed to sunlight?",
      options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
      answer: "Vitamin D",
    },
    {
      id: 3,
      question: "Which fruit is known as the king of fruits?",
      options: ["Apple", "Banana", "Mango", "Orange"],
      answer: "Mango",
    },
    {
      id: 4,
      question: "Yoga originated in which country?",
      options: ["China", "India", "Japan", "Thailand"],
      answer: "India",
    },
    {
      id: 5,
      question: "Which drink is known as an energy booster?",
      options: ["Tea", "Coffee", "Milk", "Water"],
      answer: "Coffee",
    },
    {
      id: 6,
      question: "What is the main ingredient in guacamole?",
      options: ["Tomato", "Avocado", "Cucumber", "Onion"],
      answer: "Avocado",
    },
    {
      id: 7,
      question: "How many glasses of water are recommended per day?",
      options: ["2", "4", "6", "8"],
      answer: "8",
    },
    {
      id: 8,
      question: "Which exercise is best for heart health?",
      options: ["Cardio", "Stretching", "Weightlifting", "Meditation"],
      answer: "Cardio",
    },
    {
      id: 9,
      question: "Which color symbolizes peace?",
      options: ["Red", "White", "Black", "Green"],
      answer: "White",
    },
    {
      id: 10,
      question: "Which meal is considered the most important of the day?",
      options: ["Lunch", "Dinner", "Breakfast", "Snack"],
      answer: "Breakfast",
    },
  ],
  Fun: [
    {
      id: 1,
      question: "Which animal is known as the 'Ship of the Desert'?",
      options: ["Horse", "Camel", "Elephant", "Donkey"],
      answer: "Camel",
    },
    {
      id: 2,
      question: "Which cartoon features a mouse named Jerry?",
      options: ["Tom & Jerry", "Mickey Mouse", "Looney Tunes", "Garfield"],
      answer: "Tom & Jerry",
    },
    {
      id: 3,
      question: "What is the color of the sky?",
      options: ["Red", "Blue", "Green", "Yellow"],
      answer: "Blue",
    },
    {
      id: 4,
      question: "Which instrument does a pianist play?",
      options: ["Guitar", "Drum", "Piano", "Flute"],
      answer: "Piano",
    },
    {
      id: 5,
      question: "How many colors are there in a rainbow?",
      options: ["5", "6", "7", "8"],
      answer: "7",
    },
    {
      id: 6,
      question: "Which planet is closest to the sun?",
      options: ["Mercury", "Venus", "Earth", "Mars"],
      answer: "Mercury",
    },
    {
      id: 7,
      question: "Which festival involves colors in India?",
      options: ["Diwali", "Holi", "Eid", "Christmas"],
      answer: "Holi",
    },
    {
      id: 8,
      question: "Which shape has three sides?",
      options: ["Square", "Circle", "Triangle", "Rectangle"],
      answer: "Triangle",
    },
    {
      id: 9,
      question: "Which sport uses a racket?",
      options: ["Football", "Badminton", "Cricket", "Hockey"],
      answer: "Badminton",
    },
    {
      id: 10,
      question: "What is 2 × 5?",
      options: ["7", "9", "10", "12"],
      answer: "10",
    },
  ],
};

export default quizData;
